### ISSUE TITLE
Active seeds to enable the Digibyte Testnet node

### ISSUE THREAD

**Issue by fmira21** [DigiByte-Core/digibyte#103]
Hi guys!

I am currently trying to activate a Testnet node. Looks like I need some peers to `addnode`. Can you please share a list of active ones since the list here (https://dgbwiki.com/wikifiles/DigiByteIntegration-v1.4.pdf) seems to be unreachable.

I also would be grateful for instructions on how to add nodes specifically for the Testnet.

Thank you in advance!

**Comment by fmira21** [comment]
I also would like to add some actions I have already made.

I made following digibyte.conf:

```
testnet=1

[test]
addnode=seed1.digibyte.io
addnode=seed2.digibyte.io
addnode=seed3.digibyte.io
addnode=seed.digibyte.io
addnode=seed.digibyteprojects.com
addnode=digihash.co
addnode=digiexplorer.info
addnode=seed.digibyteguide.com
addnode=seed-1.us.digibyteservers.io
```

All other arguments are passed to the container (my solution is dockerised):

```
      -server
      -testnet
      -txindex
      -rpcuser=myuser
      -rpcpassword=mypassword
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0:18333
      -rpcport=18333
      -printtoconsole=1
      -zmqpubrawblock=tcp://0.0.0.0:29000
      -zmqpubrawtx=tcp://0.0.0.0:29000
      -zmqpubhashtx=tcp://0.0.0.0:29000
      -zmqpubhashblock=tcp://0.0.0.0:29000
```

**Comment by saltedlolly** [comment]
The testnet seeders are not currently working. You can add my testnet node at 81.156.188.217. It should provide others. 

In the desktop version, you can add this by going to: Help > Debug Window. Then go to the Console tab. Type: ```addnode 81.156.188.217 add```.  I guess you should be able to put addnode=81.156.188.217 in your digibyte.conf as well.

Just a word of warning - due to a difficulty bug that affects testnet only, it can take 24 hours for a testnet node to start. Just be patient. It will get there in the end. Just don't close it or you will have to start the whole process again!

We are currently waiting on one of the devs to look at the server and figure out why the testnet seeder has gone down.

**Comment by saltedlolly** [comment]
Be sure to open port 12026 so your testnet node can be found by others.

**Comment by fmira21** [comment]
@saltedlolly 
Thank you for the answer!

I have put your IP address as follows:

```
testnet=1

[test]
addnode=81.156.188.217
```

Now I can see following in the logs:
```
connect() to 81.156.188.217:12026 failed after select(): Connection refused (111)
```
Should I wait or I did it wrong?

**Comment by saltedlolly** [comment]
Sorry, I had to restart my node due to an unrelated issue. It will take a while to restart - perhaps 24 hours.

The other week I shared some Testnet peers here: https://t.me/DigiNodeTools/451

If you don't want to wait, you can try adding them. Some of them may be out of date, but hopefully one will work.

**Comment by beggsdl** [comment]
Pavel,
You can add 24.101.88.154 also.  Other than my router periodically
rebooting, it is always up.

**Comment by fmira21** [comment]
@beggsdl 
@saltedlolly 
Guys, thank you for your help!
Now, my node is syncing!
