### ISSUE TITLE
DGB-QT IBD progress bar 

### ISSUE THREAD

**Issue by xXHenneBXx** [DigiByte-Core/digibyte#129]
No available progress bar showing on DGB 8.22-RC2

**Comment by henneb** [comment]
* DGB 8.22-RC2

**Comment by xXHenneBXx** [comment]
As well it's a really slow IBD on 8.22 vs 7.17.3

Even with added nodes

**Comment by ycagel** [comment]
Thanks for submitting. The dev team will need to look into this.

**Comment by xXHenneBXx** [comment]
Hey dev team, all it is, is in digibytegui.cpp start at line:180 
ProgressBarLabel->setVisible(false) and 
ProgressBar->setVisible(false) needs to be set true 
I can do and update if need simple task 

@ycagel @SmartArray @JaredTate @gto90 @j50ng

**Comment by ycagel** [comment]
Yes @henneb please go ahead and do the task and submit a PR for review. Thank you!

**Comment by ycagel** [comment]
@henneb Can you create a PR for this?

**Comment by ycagel** [comment]
Has this been resolved @JaredTate based on the progress bar loading?

**Comment by saltedlolly** [comment]
I just tried to compile to test this on an old laptop but it crashed out because not enough RAM. Can anyone compile it to try? the only viable system I have for compiling DigiByte Core is my M1 Macbook Pro with 32Gb RAM but I have no idea where to begin compiling on Arm. Has anyone managed to do it?

Can somebody else try tetsing this? I think he may be right about the missing progress bar but I'm not certain without comparing with and without.

**Comment by Sbosvk** [comment]
I just compiled develop branch with:

`progressBarLabel->setVisible(false);`
`progressBar->setVisible(false);`

Progress bar is working fine.
![digibyte_dev-branch_progress-bar](https://github.com/DigiByte-Core/digibyte/assets/43497491/9aecf57f-a8f1-49e4-92b4-6212f30d4051)

**Comment by ghost** [comment]
We can close this PR? Progress bar is working. @henneb

**Comment by saltedlolly** [comment]
@henneb Are you happy this is fixed? We are seeing a progress bar but maybe that was not the one you were referring to?

**Comment by ycagel** [comment]
Looks like this has been resolved. Thanks for everyone's work on it.
