### ISSUE TITLE
Testnet 8.22 RC2 Performance Issues

### ISSUE THREAD

**Issue by ycagel** [DigiByte-Core/digibyte#130]
A mining pool provided this feedback regarding 8.22 RC2 testnet.

First observation about v8.22 ( testnet)
- Syncing headers is extremely slow
- Wallet cli also very slow ( While in header sync )
~ 2 minutes for a getblockchaininfo request through digibye-cli

Using Ubuntu 22.04
CPU: Intel xeon 24core / 48 threat
RAM: 256gb DDR4

So, the wallet has finally synced the testnet chain.
However, after a restart of the wallet to change some RPC settings.
It's now hanging in "Loading block index…" for about 2 hours already.

**Comment by saltedlolly** [comment]
I am pretty sure this is the same bug we have been experiencing when running 7.17.3 when starting up testnet. It is so slow that you cannot run DigiByte Core Testnet on a Pi 4 as the syncing never catches up with the present. Starting up 7.17.3 testnet can take 15 hours or more on my old Windows laptop. It currently makes running a testnet node a pain in the ass. Evidently the problem still exists in 8.22 RC2.

This was discussed at length a few months back. @chappjc has previously shared all the details in Gitter. He also made a PR with a possible fix: https://github.com/DigiByte-Core/digibyte/pull/102

The problem only happens in testnet. Mainnet is not affected. v8 should definitely not be released until this is fixed.

**Comment by JohnnyLawDGB** [comment]
Same experience here.  I'm passed the 24 hour mark on the "Loading Block Index." "It's not a problem on mainnet, because there are blocks for each algo in mainnet. In testnet we don't have certain algos, so DigiByte-Core intensely tries to find one of these specific algo blocks. Which uses a lot of computational resources if done a few million times."  I believe it is unique to DGB because of multi-algo, and the sheer number of blocks involved.

**Comment by saltedlolly** [comment]
This is outside my knowledge of how multialgo works, but I wonder if this could be solved by finding people to mine on testnet using the algos for which no blocks have been discovered yet. This would mean that for each algo there are then at least a few blocks that exist. I wonder if that would help?

**Comment by chappjc** [comment]
@saltedlolly That's right to the heart of the issue.  I have actually had a process doing just that since April, alternating 3 of the algorithms that the built-in CPU miner can do efficiently (skein, sha256d, qubit). Note how the version alternates as you go through blocks: https://testnetexplorer.digibyteservers.io/block/2322092

However, even if it was doing all the algos, including scrypt and odo, it wouldn't change the fact that there are years of consecutive blocks that block index loading (and initial block import) has to deal with.

**Comment by saltedlolly** [comment]
@chappjc If you have been mining on testnet, and have a surplus of DGBT coins, it might be helpful for the community to send them to Renzo's Testnet Faucet: https://digifaucet.org/testnet

With a larger supply he can increase the payout per transaction. This will make it easy for anyone who needs DGBT to get some without having to mine on testnet themselves.

**Comment by saltedlolly** [comment]
With #142 merged the headers sync is much improved.

I have also encountered this issue of digibyte-cli freezing (it can freeze and take a long time before it returns a response - often several minutes).

Can anything be done?
