### ISSUE TITLE
tx fee issue

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#147]
As documented by James from CoinMinerz on 26th October on the DigiByte Discord:

"Another thing we need to address is tx fee bug to make sure anyone using RC2 or RC3 on mainnet doesn't have the mempool issue we've seen on coinminerz when payments go out. What happens is the tx fee is too low in the code and when sent it sits in mempool as it's a cheaper tx fee."

https://discord.com/channels/878200503815782400/1117868419283423293/1166363365061431417

**Comment by JaredTate** [comment]
Thanks for bringing this issue up. We increased `DEFAULT_MIN_RELAY_TX_FEE` but it appears we likely need to also increase `DEFAULT_BLOCK_MIN_TX_FEE` & maybe `DEFAULT_INCREMENTAL_RELAY_FEE` & `DUST_RELAY_TX_FEE`. 


https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/validation.h#L73


https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/policy/policy.h#L25

It looks like `DEFAULT_BLOCK_MIN_TX_FEE`  is called in BlockAssembler, so its being assembled with lower fees, then getting rejected by  `PeerManagerImpl::MaybeSendFeefilter` where `DEFAULT_MIN_RELAY_TX_FEE`  is called. 
https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/miner.cpp#L56-L59

`PeerManagerImpl::MaybeSendFeefilter` calls `DEFAULT_MIN_RELAY_TX_FEE`  and filters out TXs without high enough fees, that's why they sit in mempool. Block assembler not including high enough fee.
https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/net_processing.cpp#L4528-L4539

We should probably update these below too:

https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/policy/policy.h#L37


https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/src/policy/policy.h#L57

**Comment by ycagel** [comment]
This issue is resolved as https://github.com/DigiByte-Core/digibyte/pull/151 and https://github.com/DigiByte-Core/digibyte/pull/157 have been merged.
